version: '3.7'

volumes:
  kong_data:
    driver: local

networks:
  portal_net:
    driver: bridge

services:   
  kong_db:
    container_name: kong_db
    image: postgres:9.5
    env_file:
      - ./kong/db/environment/kong.db.env          
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    networks:
      - portal_net
    volumes:
      - kong_data:/var/lib/postgresql/data
  
  kong-migrations:
    container_name: kong-migrations
    build:
      context: ./kong
    command: kong migrations bootstrap
    depends_on:
      - kong_db
    env_file:
      - ./kong/environment/migrations.env      
    networks:
      - portal_net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong-migrations-up:
    container_name: kong-migrations-up
    build:
      context: ./kong
    command: kong migrations up && kong migrations finish
    depends_on:
      - kong_db
    env_file:
      - ./kong/environment/migrations.up.env
    networks:
      - portal_net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
   
  kong:
    container_name: kong
    build:
      context: ./kong
    depends_on:
      - kong_db
    env_file:
      - ./kong/environment/kong.env          
    networks:
      - portal_net
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "543:8543/tcp"
      - "8444:8444/tcp"    
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://kong:8001/status"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  konga-prepare:
    container_name: konga-prepare
    build:
      context: ./konga
    command: "-c prepare -a postgres -u postgresql://kong:Pa55w0rd@kong_db:5432/konga_db"
    networks:
      - portal_net
    restart: on-failure
    depends_on:
      - kong_db

  konga:
    container_name: konga
    build:
      context: ./konga
    restart: always
    networks:
      - portal_net
    env_file:
      - ./konga/environment/konga.env      
    depends_on:
      - kong_db
    ports:
      - "1337:1337"